# Generated by Django 4.2.29 on 2026-03-13 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0027_image_description'),
        ('home', '0004_productpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='collection_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='collection_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='collection_subtitle',
            field=models.CharField(blank=True, help_text='Маленький текст над заголовком, например: КОЛЛЕКЦИЯ · 2026', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='collection_title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
